sudo: required
dist: trusty
language: generic
before_install:
# update the system
- sudo apt-get -qq update
# install the newest version of texlive
- git clone https://github.com/cryptofuture/install-tl-ubuntu.git
- cd install-tl-ubuntu
- sudo ./install-tl-ubuntu
- eval "$(sed 's/^/export /' /etc/environment)"
- cd ..
script:
# create files for gitinfo2
- wget "https://raw.githubusercontent.com/Hightor/gitinfo2/CTAN/post-xxx-sample.txt" -O generate_gitinfo2
- chmod +x generate_gitinfo2
- ./generate_gitinfo2
# build the pdf file
- chmod +x make
- ./make
# move the file for deployment 
- mkdir github-pages
- mv notes.pdf github-pages/representation_theory_1_notes.pdf

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN	# defined in travis dashboard
  target_branch: gh-pages
  local_dir: github-pages
  on:
    branch: master

notifications:
  email: false
